/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RdtHead {
        "logoImage": string;
    }
    interface RdtIndex {
    }
}
declare global {
    interface HTMLRdtHeadElement extends Components.RdtHead, HTMLStencilElement {
    }
    var HTMLRdtHeadElement: {
        prototype: HTMLRdtHeadElement;
        new (): HTMLRdtHeadElement;
    };
    interface HTMLRdtIndexElement extends Components.RdtIndex, HTMLStencilElement {
    }
    var HTMLRdtIndexElement: {
        prototype: HTMLRdtIndexElement;
        new (): HTMLRdtIndexElement;
    };
    interface HTMLElementTagNameMap {
        "rdt-head": HTMLRdtHeadElement;
        "rdt-index": HTMLRdtIndexElement;
    }
}
declare namespace LocalJSX {
    interface RdtHead {
        "logoImage"?: string;
    }
    interface RdtIndex {
    }
    interface IntrinsicElements {
        "rdt-head": RdtHead;
        "rdt-index": RdtIndex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rdt-head": LocalJSX.RdtHead & JSXBase.HTMLAttributes<HTMLRdtHeadElement>;
            "rdt-index": LocalJSX.RdtIndex & JSXBase.HTMLAttributes<HTMLRdtIndexElement>;
        }
    }
}
