/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutPage {
    }
    interface PortfolioChart {
    }
    interface PortfolioPage {
    }
}
declare global {
    interface HTMLAboutPageElement extends Components.AboutPage, HTMLStencilElement {
    }
    var HTMLAboutPageElement: {
        prototype: HTMLAboutPageElement;
        new (): HTMLAboutPageElement;
    };
    interface HTMLPortfolioChartElement extends Components.PortfolioChart, HTMLStencilElement {
    }
    var HTMLPortfolioChartElement: {
        prototype: HTMLPortfolioChartElement;
        new (): HTMLPortfolioChartElement;
    };
    interface HTMLPortfolioPageElement extends Components.PortfolioPage, HTMLStencilElement {
    }
    var HTMLPortfolioPageElement: {
        prototype: HTMLPortfolioPageElement;
        new (): HTMLPortfolioPageElement;
    };
    interface HTMLElementTagNameMap {
        "about-page": HTMLAboutPageElement;
        "portfolio-chart": HTMLPortfolioChartElement;
        "portfolio-page": HTMLPortfolioPageElement;
    }
}
declare namespace LocalJSX {
    interface AboutPage {
    }
    interface PortfolioChart {
    }
    interface PortfolioPage {
    }
    interface IntrinsicElements {
        "about-page": AboutPage;
        "portfolio-chart": PortfolioChart;
        "portfolio-page": PortfolioPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-page": LocalJSX.AboutPage & JSXBase.HTMLAttributes<HTMLAboutPageElement>;
            "portfolio-chart": LocalJSX.PortfolioChart & JSXBase.HTMLAttributes<HTMLPortfolioChartElement>;
            "portfolio-page": LocalJSX.PortfolioPage & JSXBase.HTMLAttributes<HTMLPortfolioPageElement>;
        }
    }
}
