name: Create Tag
on:
  [workflow_dispatch]

permissions: read-all|write-all

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Create Release Tag
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Create tag
        run: |
          DATE=$(date +"%Y%m%d-%H%M%S")
          git tag $DATE -m "$DATE"
          git push --tags "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
